### ISSUE TITLE
CaRMS data

### ISSUE THREAD

**Issue by DaxBourcier** [canadian-federation-of-medical-students/CFMS-Issue-Tracker#73]
Hey Justin,

The data doesn't seem to show up for all regions. I tried different specialties and there's always random regions with missing data. Here's an example using neurology.

![image](https://user-images.githubusercontent.com/62123024/93023896-b52b4e80-f5c8-11ea-9505-9d6274ee05d1.png)

**Comment by DaxBourcier** [comment]
Also I just remembered this, but CaRMS gives us the # of applicatIONS and also the # of distinct applicANTS. We want to use the # of distinct applicants as the data set that fills out the Number of CMG applicants. I know we had confrimed this at the meeting with Michel but wanted to double check to make sure. Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier This should now be fixed. The GeoJSON was referencing the wrong id for Quebec and Ont.

I also Added Canada to the CaRMS GeoJSON View, since it encapsulates a lot of this data.



For the Distinct CaRMS Applications. This is fine. I would suggest we do 1 of the following though:

1. Reach out to CaRMS and have them stop sending the Number of Applications if we are going to omit this Dataset from the HHRTF Platform going forward
2.) Make it explicitly clear Going forward that we are ONLY importing the Distinct Value.

I can just foresee this being an issue in the future, where someone will upload the # of CMG Applicants versus the Distinct Dataset. Which will cause discrepancies in our data


I will update the CaRMS Data, and flush out the bad Data, adding Distinct for the # of CMG applicants! I will update you when it's finished

**Comment by Jrschellenberg** [comment]
@DaxBourcier The data is now updated to reflect 
`Number of CMG applicants (distinct)`

**Comment by DaxBourcier** [comment]
Sounds good, will do this, thanks!

**Comment by Jrschellenberg** [comment]
Perfect! Closing this ticket for now

**Comment by DaxBourcier** [comment]
Hey Justin, the West region still appears to be broken:

![image](https://user-images.githubusercontent.com/62123024/93030629-cd1bc600-f5fa-11ea-9906-89843ffb1ea2.png)

**Comment by Jrschellenberg** [comment]
@DaxBourcier Please take a look. There was an issue again with the GeoJson id's being out of sync from the DB, Should be good to go now! If it is, we can close this ticket

**Comment by Jrschellenberg** [comment]
@DaxBourcier Closing this unless you find another issue with it. Please reopen and let me know!

**Comment by DaxBourcier** [comment]
Atlantic region is coming empty on two of the CaRMS data sets on about half the specialties I tried:

![image](https://user-images.githubusercontent.com/62123024/93158858-67573900-f6e3-11ea-89ed-14f66e8f27f7.png)

I'm pretty positive this data was provided to us by CaRMS. If possible to double check and confirm this isn't a similar issue that happened like the other regions. 

Thanks!

**Comment by DaxBourcier** [comment]
Sorry just saw your last email on how to find Excel data. (i'm going up the email list hahaha). If possible to check this one (just because we had issues with CaRMS previously and the others I'll do the excel trick. Thanks!

**Comment by Jrschellenberg** [comment]
@DaxBourcier 

Sounds good! Let me know! It is possible perhaps I was using the wrong Data? I was using the Data found under Original Requests,

I then copied the template and built the Adapter. The Data I imported is in Tab 3 And CaRMS original Input is located in Tab 1

**Comment by DaxBourcier** [comment]
Everything is good.
